### ISSUE TITLE
Resolve error "calling needs :cxx11 is disabled"

### ISSUE THREAD

**Issue by bencomp** [fbkarsdorp/homebrew-lamachine#15]
Today, when updating Homebrew and packages, `brew update && brew upgrade` failed with the error:

```
Error: Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the fbkarsdorp/lamachine tap:
  /usr/local/Homebrew/Library/Taps/fbkarsdorp/homebrew-lamachine/Formula/mbt.rb:10
```
Line 10 in mbt.rb is `needs :cxx11`. I'm guessing that this specific syntax is no longer allowed by Homebrew. Looking at [formulae in Homebrew-core that call `ENV.cxx11`](https://github.com/Homebrew/homebrew-core/search?q=cxx11&unscoped_q=cxx11), maybe it's not necessary to even use `needs :cxx11`, as I haven't seen it elsewhere.

**Comment by fbkarsdorp** [comment]
Thanks for this. I just removed the requirement. Could you try again?

**Comment by bencomp** [comment]
That was quick! `brew update && brew upgrade` now works again. Thanks!
