### ISSUE TITLE
Brew make error when installing Timbl

### ISSUE THREAD

**Issue by antalvdb** [fbkarsdorp/homebrew-lamachine#18]
$ brew install timbl
==> Fetching fbkarsdorp/lamachine/timbl
==> Downloading https://github.com/LanguageMachines/timbl/releases/download/v6.9
Already downloaded: /Users/antalb/Library/Caches/Homebrew/downloads/768d67531c467347107be8357694eeb636b9d30e49d539e48f3e8b47c804828c--timbl-6.9.tar.gz
==> Installing timbl from fbkarsdorp/lamachine
==> ./configure --disable-silent-rules
==> make install
Last 15 lines from /Users/antalb/Library/Logs/Homebrew/timbl/02.make:
   76 | uset_close_76
      | ^~~~~~~~~~~~~
/opt/homebrew/Cellar/icu4c@76/76.1_1/include/unicode/localpointer.h:551:68: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
  551 |     using LocalPointerClassName = internal::LocalOpenPointer<Type, closeFunction>
      |                                                                    ^~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [IBtree.lo] Error 1
20 errors generated.
make[1]: *** [IBprocs.lo] Error 1
20 errors generated.
make[1]: *** [MBLClass.lo] Error 1
20 errors generated.
make[1]: *** [GetOptClass.lo] Error 1
make: *** [install-recursive] Error 1

Full make log:
[02.make.log](https://github.com/user-attachments/files/18005196/02.make.log)

**Comment by kosloot** [comment]
Might have to do with c++ versions. The latest timbl version in Git will use c++17 which might solve this
A new  release is planned later this year

**Comment by proycon** [comment]
The new timbl was released and packaged, this bug should be solved now.
