### ISSUE TITLE
ucto does not install

### ISSUE THREAD

**Issue by antalvdb** [fbkarsdorp/homebrew-lamachine#2]
==> Installing fbkarsdorp/lamachine/frog dependency: ucto
==> Downloading https://github.com/LanguageMachines/ucto/releases/download/v0.11
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/ucto/0.11
==> make install
==> make check
Last 15 lines from /Users/antalb/Library/Logs/Homebrew/ucto/03.make:
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to lamasoftware@science.ru.nl
============================================================================
make[3]: *** [test-suite.log] Error 1
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

**Comment by fbkarsdorp** [comment]
@antalvdb, could you show the brew logs in `~/Library/Logs/Homebrew/ucto/config.log`

**Comment by antalvdb** [comment]
[config.log](https://github.com/fbkarsdorp/homebrew-lamachine/files/1727244/config.log)

**Comment by fbkarsdorp** [comment]
OK. I added some bottles from the old science tap. @antalvdb could you do a

`brew update`

followed by

`brew install ucto`

?

**Comment by antalvdb** [comment]
==> Installing ucto from fbkarsdorp/lamachine
==> Installing dependencies for fbkarsdorp/lamachine/ucto: uctodata
==> Installing fbkarsdorp/lamachine/ucto dependency: uctodata
==> Downloading https://github.com/LanguageMachines/uctodata/releases/download/v
Already downloaded: /Users/antalb/Library/Caches/Homebrew/uctodata-0.5.tar.gz
==> bash bootstrap.sh
Last 15 lines from /Users/antalb/Library/Logs/Homebrew/uctodata/01.bash:
2018-02-15 12:40:07 +0100

bash bootstrap.sh

bootstrap.sh: line 67: automake: command not found
bootstrap.sh: line 76: aclocal: command not found
bootstrap.sh: line 89: autoreconf: command not found

**Comment by fbkarsdorp** [comment]
Ah, sorry. I didn't push the change. Should be working now.

**Comment by antalvdb** [comment]
[config.log](https://github.com/fbkarsdorp/homebrew-lamachine/files/1727525/config.log)

**Comment by fbkarsdorp** [comment]
Could you do it like this? `brew update && brew uninstall ucto && brew install ucto`

**Comment by antalvdb** [comment]
does not work -- already uninstalled it

MAC11-363:gplural antalb$ brew update && brew uninstall ucto && brew install ucto
Already up-to-date.
Error: No such keg: /usr/local/Cellar/ucto
MAC11-363:gplural antalb$ brew uninstall ucto
Error: No such keg: /usr/local/Cellar/ucto
MAC11-363:gplural antalb$ brew install ucto
==> Installing ucto from fbkarsdorp/lamachine
==> Downloading https://homebrew.bintray.com/bottles-lamachine/ucto-0.11.high_si

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "ucto"
Download failed: https://homebrew.bintray.com/bottles-lamachine/ucto-0.11.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/LanguageMachines/ucto/releases/download/v0.11
Already downloaded: /Users/antalb/Library/Caches/Homebrew/ucto-0.11.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/ucto/0.11
==> make install
==> make check
Last 15 lines from /Users/antalb/Library/Logs/Homebrew/ucto/03.make:
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to lamasoftware@science.ru.nl
============================================================================
make[3]: *** [test-suite.log] Error 1
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/fbkarsdorp/homebrew-lamachine/issues

**Comment by kosloot** [comment]
As you can see, (could have seen....)  ucto IS installed and running. But the 'make check' failed.
This might be caused by an incomplete installation (maybe uctodata is not installed?)

To get an answer: the program says what to do:
**See src/test-suite.log**
so.....

**Comment by fbkarsdorp** [comment]
Yes, it installs but there is a linking problem...

```
❯ ucto -L generic 
ucto: inputfile = 
ucto: outputfile = 
dyld: lazy symbol binding failed: Symbol not found: __Z12textcat_InitPKc
  Referenced from: /usr/local/Cellar/ucto/0.11/lib/libucto.3.dylib
  Expected in: flat namespace

dyld: Symbol not found: __Z12textcat_InitPKc
  Referenced from: /usr/local/Cellar/ucto/0.11/lib/libucto.3.dylib
  Expected in: flat namespace

[1]    46240 abort      ucto -L generic
```

**Comment by kosloot** [comment]
Aha...
yes, libtextcat should be installed (tapped) and added to LD flags and CXX flags
I solved this in the git version already, but that doesn't help you for now.
something like:
``
 CXXFLAGS="$CXXFLAGS -I<BLA>/include/libtextcat"
``
``
LDFLAGS="-L<BLI> -ltextcat $LDFLAGS"
``
But I don't have BLA and BLI at hand now. @proycon didn't you use this for LaMachine?

**Comment by kosloot** [comment]
This will do probably:
``
CXXFLAGS="$CXXFLAGS -I/usr/local/include/libtextcat"
``
``
LDFLAGS="-ltextcat $LDFLAGS"
``
as BLI equals /usr/local/lib, which should be in your path

**Comment by fbkarsdorp** [comment]
Thanks @kosloot . What's supposed to be in LDFLAGS *before* prepending "-ltextcat"?

**Comment by kosloot** [comment]
That can be a lot.
Ii ss filled in by configure and pkg-config, don't bother...
Typically:
``-lreadline /usr/local/lib/libticcutils.dylib -licuio -licui18n -licuuc -licudata -lz -lbz2 -ltar -lboost_regex-mt -lxml2``

see config.log

**Comment by fbkarsdorp** [comment]
Right. For some reason, Homebrew ignores them all... We're getting somewhere!

**Comment by fbkarsdorp** [comment]
@antalvdb I've just update the formulas to the most recent releases. Would be great if you could try again.

**Comment by antalvdb** [comment]
it works!
