### ISSUE TITLE
Different libxml2 used for ticcutils, libfolia and ucto

### ISSUE THREAD

**Issue by fbkarsdorp** [fbkarsdorp/homebrew-lamachine#6]
Ticcutils uses the default libxml2 library that comes with macOS, yet libfolia and ucto attempt to use brew's version. I can't seem to force brew to use the default one instead. Is this somehow covered in the makefile, @proycon ?

**Comment by proycon** [comment]
@kosloot has done a lot of improvements for mac compatibility lately, but I think most of those aren't released yet. He'll know more about it. It's probably best idea to prepare new releases.

**Comment by kosloot** [comment]
I am not aware of any differences for libxml2 in the configure steps for ticcutils versus libfolia.
They both use pkg-config. And do that for a long time, afaik
But @proycon is right that I changed a lot in the configuration lately, and new releases are needed, but this will take another week (or so :P )
