### ISSUE TITLE
New releases to brew

### ISSUE THREAD

**Issue by kosloot** [fbkarsdorp/homebrew-lamachine#7]
I updated on GitHub the releases of:
- ticcutils
- libfolia
- ucto
- foliautils
- ticcltools
- frog

Maybe it is good to see how this affects the brewing?

**Comment by fbkarsdorp** [comment]
Great. I'll get to work.

**Comment by fbkarsdorp** [comment]
OK. Thanks a lot Ko. With some tweaking, I managed to get it all compiled and running! 🎉

**Comment by fbkarsdorp** [comment]
Confirmation.
